mike42/escpos-php

- src/EscposImage.php
fixed function call    
imagecreatefromjpg() -> imagecreatefromjpeg()
> fixed EscposImage function name - imagecreatefromjpeg()

- src/WindowsPrintConnector.php
> fixed runCommand() $cmd undefined variable

- README.md
add new device thermal receipt printer that work with this driver
> support for Silicon SP-201 / RP80USE,

- src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php
Changes to error output as required for #156
> Improve WindowsPrintConnector error output

- README.md
> Add Rongta RP326US to README

- README.md
> Add Venus V248T to printer list

- README.md
This printer supports ESC/POS, researched for #152
> Add Gainscha GP-U80300I ESC/POS printer

- README.md
> Add Excelvan ZJ-8220 to printer list

- example/print-from-html.php
> Fix incorrect EscposImage usage

- README.md
Contained both old and new usage, but only new usage should appear.
> Fix to capabilities example in README

- README.md
These link to the packagist repository, to encourage developers to get the code through composer.
> Add extra badges to README

- README.md
Printer is known to work.
Reference:
- #204
> Add Hasar HTP 250

- README.md
- composer.json
- src/Mike42/Escpos/PrintBuffers/EscposPrintBuffer.php
- test/unit/EscposPrintBufferTest.php
- Add Hasar HTP 250 to list of printers known to work
- Fixes to allow the use of Windows line endings in input text
> Changes for release 1.4.1

- example/specific/141-custom-command.php
Example for developers who want to send binary to the print connector directly.
Reference-
- #141
> Add example

- README.md
> Add Star TSP100 ECO to README

- CONTRIBUTING.md
> Create "How to contribute" page

- example/specific/235-get-data.php
> New example

- doc/FAQ.md
This pull request corrects some spelling mistakes, and adjusts the FAQ to answer the common question
- "I have Printer X. Can I use this driver?".
> FAQ: Split up common printer compatibility questions

- README.md
> Adds Excelvan HOP-E200 to known printer list

- README.md
> Add to known printers

- README.md
> Add Epson TM-T88V

- src/Mike42/Escpos/ImagickEscposImage.php
I just test the code, but i think it's a mistype.
> Mistype in ImagickEscposImage.php

- README.md
- composer.json
- composer.lock
This pull request addresses minor documentation and dependency issues.
Issue references:
- #279
- #262 
- #300 
This includes an update to `composer.lock`, so the versions of some development dependencies may have changed.
> Maintenance update

- README.md
> Add Rongta RP58-U

- CONTRIBUTORS.md
- src/Mike42/Escpos/PrintConnectors/UriPrintConnector.php
- test/unit/UriPrintConnectorTest.php
This adds the UriPrintConnector contributed by @evsar3.
Reference:
- #314
> Add UriPrintConnector

- CONTRIBUTING.md
> Update supported PHP versions in CONTRIBUTING.md

- src/Mike42/Escpos/resources/capabilities.json
This pull request updates the [receipt-print-hq/escpos-printer-db](https://github.com/receipt-print-hq/escpos-printer-db) dependency to include changes to the database made since the previous release.
> Capabilities DB update

- src/Mike42/Escpos/resources/capabilities.json
This brings in a new printer profile for the TM-T88IV.
Ref:
- #544
> Update receipt printer database

- src/Mike42/Escpos/resources/capabilities.json
Update to receipt printer database only.
> Changes for release 2.0.1

- src/Mike42/Escpos/Printer.php
My IDE is starting complaining about this kind of things
> Typo in Printer.php
