mike42/escpos-php

src/WindowsPrintConnector.php

I think runCopy() needs some error handling.
At this point I just return copy() result and if its not true throw Exception.
Will try to write some tests also ;)

throw exception when copy to printer failed

---

src/Mike42/Escpos/Printer.php

This method allows a user to set the element width of the barcode which is handy when printing long barcodes.

Added method to set width of a barcode on Printer

---

example/specific/6-arabic-epos-tep-220m.php
src/Mike42/Escpos/PrintBuffers/ImagePrintBuffer.php

This pull request corrects a bug that stopped `ImagePrintBuffer` from working, adds font handling support to `ImagePrintBuffer`, and updates the Arabic text example to use a configured TTF font.
Tested on Epson TM-T20II.
References:
- #31
- #134

Fixes to ImagePrintBuffer and Arabic example

---

src/Mike42/Escpos/PrintBuffers/EscposPrintBuffer.php
test/unit/EscposPrintBufferTest.php

Skip past LF ("\r") character rather than writing a question mark.
Previously, "\r\n" would cause "?\n" to appear in the output, but now "\r\n" is wound back
to "\n" on its own.
Reference:
- #209

Windows line endings: Special handling for LF character

---

.coveralls.yml
.gitignore
.travis.yml
README.md
phpunit.xml

This pull request introduces "Coverall" coverage reports to the build.
A coverage badge is displayed on the README, and the PHPUnit configuration has also moved.
Ref: 
- #192

Add coverage reporting to build process

---

.travis.yml

Minor tweaks to CI build plan
- Install imagick extension on versions where it is available - coverage is improved, since some tests are skipped if the extension is missing
- PHP 7.1 is now available

Test improvements

---

composer.json
composer.lock
phpunit.xml

This pull request is a maintenance update to some dependencies
- formats the `composer.json` file
- updates dependency versions
- adds `mbstring` version as dependency
- clarifies that the code cannot be tested on php before `5.3.9` (a `require-dev` dependency has this limit)
- removes deprecated phpunit `strict` option
- sets the composer platform config to `5.3.9`, so that `composer update` does not introduce updates which depend on PHP versions that we are missing in one of our test environments
Reference:
- #201

Dependency updates

---

doc/FAQ.md

I've been forced recently to make the switch to from server side to client side printing and have found this SDK to be exactly what I needed. 
I've been using escpos-php for a while and it's **awesome**. It took me quite a while (and a lot of stress) to find a viable client side alternative so I wanted to share it with others that might be in the same situation.
Note: I'm not sure why github thinks I changed line 136, I only added line 108.

Add link to ePOS-Device SDK for JavaScript in FAQ

---

LICENSE.md

White-space and header changes to license, to match GitHub template.
Currently, GitHub does not recognize that this is MIT license, hoping to fix.

Update LICENSE.md for GitHub recognition

---

src/Mike42/Escpos/Printer.php

This pull request adjusts some visibility from `private` to `protected`, so that sub-classes can extend the `Printer` class easily.
Reference:
- #249

Method and field visibility

---

composer.json
composer.lock
src/Mike42/Escpos/PrintConnectors/ApiPrintConnector.php

This connector will send print jobs to this [print server API app](https://github.com/ablunier/escpos-print-api).
If your printer is in a different network than your webapp and you can't stand up a VPN, you can install this API in your printer's network and connect with it from your webapp with this new connector.

New ApiPrintConnector

---

.travis.yml

Minor correction to Travis CI, as broken `phpunit` on PHP nightly is not passing as expected.
Issue reference:
- N/A
Before:
After:

Allows PHP nightly to fail

---

src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php

This pull request corrects a bug in the `WindowsPrintConnector` when names like `LPT1` or `COM1` are used.
The `file_put_contents()` call here is incorrect, causing the print to fail.
Issue reference:
- #277

Corrects bug in file_put_contents call

---

src/Mike42/Escpos/resources/capabilities.json

This pull request replaces the capabilities database with the latest upstream, for printers to include in the v1.5 release.
- OCD-300
- POS-5890
- Inclusion of the new `pdf417code` feature flag.

Update db to current upstream master

---

composer.json
src/Mike42/Escpos/ImagickEscposImage.php

This is not required for most users, and had introduced a break in compatibility.
Issue reference:
- #300

Relax "guzzlehttp/guzzle" dependency

---

src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php

Default to ini_get(‘default_socket_timeout’) or 60 seconds
Closes #348

Add timeout parameter to NetworkPrintConnector

---

.travis.yml
test/integration/ExampleTest.php

This pull request brings the build back into a passing state. It has been failing due to Travis CI changes.
- disable HHVM, which no longer installs
- remove PHP 5.3, which also no longer installs
- add ghostscript install, solves "error running delegate" on Travis CI
Skip integration tests that are not bit-for-bit repeatable on Travis CI.
Was able to confirm that the "expected" and "actual" output are different in the way that the image is converted to pure black & white. It would be ideal to have this repeatable, but pure black & white images will not be affected.
Animation below toggles between the images contained in the outputs:

Remove broken build steps

---

README.md

This pull request is a bulk update to the list of supported printers based on reports from users.
- Citizen CT-S310II #335
- Epson TM-T20II #322
- Epson TM-T81 #373
- Epson TM-U590 and TM-U590P #415
- Equal (EQ-IT-001) POS-58 #421
- Metapace T-25 #383
- Nexa PX700 #444
- Orient BTP-R580 #400
- Star TSP100III FuturePRNT #449
- XPrinter XP-Q20011 #340
- Xprinter XP-80C #401

Add newly tested printers to README

---

src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php

Today I had a problem while using a password with the + character. The library was throwing the BadMethodCallException located at line 155. So, to avoid it I added the + character in the REGEX_SMB constant. This will allow the connector to work with passwords that have such symbol. It would be a good idea to allow more special characters on passwords. I guess a little research would be needed to know which ones should be allowed.

About REGEX_SMB constant

---

README.md
src/Mike42/Escpos/Printer.php
test/unit/EscposTest.php

EPSON TM-U295 slip printer requires a `ESC q` sequence to release the paper. It adds a simple command to make this available.
Related documentation from TM-U295 Documentation

Release paper function for EPSON TM-U295

---

README.md

Epson TM-T88II is confirmed to be working.

Add Epson TM-T88II to README.md

---

.travis.yml
README.md
composer.json
composer.lock
src/Mike42/Escpos/CapabilityProfile.php
src/Mike42/Escpos/EscposImage.php
src/Mike42/Escpos/ImagickEscposImage.php
src/Mike42/Escpos/PrintBuffers/EscposPrintBuffer.php
src/Mike42/Escpos/PrintConnectors/ApiPrintConnector.php
src/Mike42/Escpos/PrintConnectors/DummyPrintConnector.php
src/Mike42/Escpos/PrintConnectors/FilePrintConnector.php
src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php
src/Mike42/Escpos/Printer.php

This pull requests bumps the minimum required PHP version to 5.4.0, and updates documentation and dependencies accordingly.
PHP 5.3 users either upgrade their PHP, or run the 1.x branch of escpos-php. To ensure that we don't carry any PHP 5.3 users into this version, `composer.json` has been updated with the new minimum, and the `array()` syntax has intentionally been replaced with `[]`, which will only work on PHP 5.4 and above.
Reference:
- #530

Dependency update

---

src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php
test/unit/WindowsPrintConnectorTest.php

Updates #488, which could not be merged due to build system issues.

Set SMB2 as default highest allowed protocol (Updated)

---

src/Mike42/Escpos/PrintConnectors/WindowsPrintConnector.php

Set SMB2 as default highest allowed protocol

---

README.md

This pull request collects updates to the list of printers that have been reported to work by the user-base:
- Senor TP-100 #528
- 3nStrat POS-08  #527
- Black Copper BC-85AC #517
- Nyear NP100 #499
- Star BSC10 #487
- Sicar POS-80 #483
- Bematech-4200-TH #472
- Xprinter XP-90, XP-58 Series #463
- Dapper-Geyi Q583P #296 
- Epson EU-T332C #276

Update printer list & sort

---

.travis.yml
README.md

As in title.
We previously tested on whichever version were available, but these were broken on Travis CI at some point.
Ref:
- #530 
- #396

Include HHVM 3.21 LTS compatiboility for 2.0 release

---

README.md

This change adds a number of printers to the README, which have been tested by users of this driver.
- OKI RT322 #684
- ithaca ITherm 280 #664
- Rongta RP80USE #641
- Sewoo SLK-TS400 #639
- Approx APPPOS80AM #638
- QPOS Q58M #635
- HOIN HOP-H58 #632
- Xeumior SM-8330 #625
- Birch PRP-085III #619
- 3nStar RPT-008 #610
- POSLIGNE ODP200H-III-G #555

Add newly tested printers to list

---

src/Mike42/Escpos/CodePage.php
src/Mike42/Escpos/ImagickEscposImage.php
src/Mike42/Escpos/PrintConnectors/NetworkPrintConnector.php
src/Mike42/Escpos/Printer.php
test/integration/ExampleTest.php
test/unit/GdEscposImageTest.php

Hi! This PR fixes #879.
Add `declare(strict_types=1);` to:
For each class, I have:
1. added strict_types;
1. ran tests;
1. and fixed the actual code.
* In general, I only made some castings to fix.
----
This was the trickiest fix: https://github.com/mike42/escpos-php/commit/0c5d2694752c77590a899aa661e8a72e710375bd. Check the commit message for more details. It would be a good idea to upgrade PHP.

Add strict types to CodePage, ImagickEscposImage, NetworkPrintConnector and Printer and fix the code

---

.travis.yml
README.md
composer.json
composer.lock
src/Mike42/Escpos/GdEscposImage.php
test/integration/ExampleTest.php
test/unit/AuresCustomerDisplayTest.php
test/unit/EscposPrintBufferTest.php
test/unit/EscposTest.php
test/unit/Experimental/Unifont/UnifontPrintBufferTest.php
test/unit/ImagickEscposImageTest.php
test/unit/UriPrintConnectorTest.php

This change:
- drops support for PHP 7.0, 7.1 and 7.2
- introduces support for PHP 8.0
- updates build and test dependencies, documentation as necessary

Change supported php versions, apply 8.0 fixes and build environment changes
